# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smaller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smallurl',
            old_name='new_url',
            new_name='newurl',
        ),
    ]
