# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smaller', '0002_auto_20170410_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallurl',
            name='newurl',
            field=models.CharField(blank=True, default='None', max_length=20, null=True),
        ),
    ]
