# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smaller', '0004_auto_20170411_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
