# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 15:28
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('smaller', '0005_smallurl_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='smallurl',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
